### ISSUE TITLE
Trojan in Release 1.3.3?

### ISSUE THREAD

**Issue by Stephan-P** [0xC0000054/pdn-cameraraw#1]
Microsoft Defender reports Trojan: Win32/Wacatac.H!ml and refuses to download the zip file. 
No way to circumvent this, it appears.

**Comment by 0xC0000054** [comment]
Looks like a false positive, none of the other vendors on VirusTotal have an issue with the file.
https://www.virustotal.com/gui/file/50863cd88deb6215613d27138c36c751a834422d860370d0b3c27d14a65bc58c?nocache=1

**Comment by Stephan-P** [comment]
Unlike other possible false positives, there is no way for me to report this file. (why?)
Could the project manager upload and report it to Microsoft Security?
For me, it's the waiting game until the download falls through.

**Comment by Stephan-P** [comment]
MS fixed their issue. 
Download completed
